### ISSUE TITLE
precompilation error in Julia 1.9 RC3

### ISSUE THREAD

**Issue by truedichotomy** [korsbo/Latexify.jl#264]
Not sure what's the root cause but Latexify currently fails to precompile on Julia 1.9 RC3. I don't have Latexify explicitly installed, it's installed as a dependency to another package.

```
(@v1.9) pkg> precompile
Precompiling project...
  ✗ Latexify → ParameterizedFunctionsExt
  0 dependencies successfully precompiled in 2 seconds. 630 already precompiled.
```

versioninfo():
```
julia> versioninfo()
Julia Version 1.9.0-rc3
Commit 1853b90328* (2023-04-26 15:51 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by ggebbie** [comment]
Hi Donglai -- nice to see you here. I confirm the same issue with 1.9.0-rc2 on Linux Ubuntu OS.  Some of the other recent filed Latexify issues may be related to this one, but I'm not 100% sure.

**Comment by korsbo** [comment]
Hi, this _should_ have been fixed in Latexify 0.15.21. I released this version a few minutes ago and it should become available to all in a couple of hours. Please let me know if the problem persists after that.

**Comment by ggebbie** [comment]
updated and works with Latexify 0.16.0, julia 1.9.0-rc3, where Latexify was a dependency of Plots

thank you!

**Comment by truedichotomy** [comment]
@ggebbie, good to see you here as well! I can confirm that Latexify 0.16.0 is working for me. Thanks for the quick fix @korsbo.
